"""Report what is inside a Pole Position workstation backup, by category.

A workstation backup sweeps the whole station data directory, so it grows with
everything the station has ever accumulated -- not only the configuration,
recipes, and models a replacement workstation actually needs. This report shows
where the bytes went, and separates content a replacement station requires from
content it can regenerate.

    python scripts/analyze_station_backup.py "C:\\path\\to\\backup.zip"

It reads the archive without extracting it, so it is safe to run against a
production backup.
"""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path

# (label, matcher, essential, note)
#
# "Essential" means a replacement workstation cannot be commissioned without it.
# Everything else is either regenerated by normal production, rebuilt on demand
# from data that is itself backed up, or a migration leftover.
CATEGORIES: list[tuple[str, str, bool, str]] = [
    ("Station configuration", "config.json", True, "settings and backend selection"),
    ("Backup manifest", "pole_position_backup.json", True, "per-file checksums and provenance"),
    ("Recipe database", "runtime/battery_inspector.db", True, "recipes, revisions, audit history"),
    ("Recipe references", "runtime/recipes/", True, "immutable per-revision reference images"),
    ("Validation evidence", "runtime/validation/", True, "guided qualification records"),
    ("Installed models", "runtime/models/", True, "qualified ONNX package bound to recipes"),
    ("Portable ML assets", "portable_ml/", True, "model files configured outside the data directory"),
    ("ML training samples", "runtime/ml_training/samples/", True, "taught crops; costly to recapture"),
    (
        "ML prepared dataset",
        "runtime/ml_training/datasets/",
        False,
        "train/val/test copies of the samples above; rebuilt by the wizard",
    ),
    (
        "ML training runs",
        "runtime/ml_training/runs/",
        False,
        "checkpoints and plots from past training; regenerable",
    ),
    (
        "ML staging",
        "runtime/ml_training/staging/",
        False,
        "captures not yet committed to the sample store",
    ),
    # Catch-all for the sample store's own bookkeeping (samples.jsonl and any
    # loose files). Must stay below the ml_training subcategories above, which
    # are matched in order and are more specific.
    (
        "ML training index",
        "runtime/ml_training/",
        True,
        "sample-store manifest describing the taught crops",
    ),
    (
        "Failure evidence",
        "runtime/inspections/",
        False,
        "retained non-PASS cycles; retention-bounded and re-accumulated in production",
    ),
    ("Recipe staging", "runtime/recipe_staging/", False, "in-progress wizard captures"),
    (
        "Pre-v0.17 archive",
        "runtime/archive_pre_v017_",
        False,
        "bench data moved aside at the v0.17 migration and never cleared",
    ),
]


def classify(name: str) -> tuple[str, bool, str]:
    for label, matcher, essential, note in CATEGORIES:
        if name == matcher or name.startswith(matcher):
            return label, essential, note
    return "Other", True, "unclassified; counted as essential to stay conservative"


def human(size: float) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            return f"{size:,.1f} {unit}" if unit != "B" else f"{int(size)} B"
        size /= 1024
    return f"{size:,.1f} TB"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Report the size breakdown of a Pole Position workstation backup."
    )
    parser.add_argument("backup", type=Path, help="Path to the backup .zip")
    parser.add_argument(
        "--top",
        type=int,
        default=15,
        help="How many of the largest individual entries to list (default 15).",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of a report.")
    arguments = parser.parse_args()

    if not arguments.backup.is_file():
        print(f"Backup not found: {arguments.backup}")
        return 2

    totals: dict[str, dict[str, object]] = {}
    entries: list[tuple[int, str]] = []
    stored_total = 0
    compressed_total = 0

    with zipfile.ZipFile(arguments.backup) as archive:
        manifest = {}
        try:
            manifest = json.loads(archive.read("pole_position_backup.json").decode("utf-8"))
        except (KeyError, UnicodeDecodeError, json.JSONDecodeError):
            pass

        for info in archive.infolist():
            if info.is_dir():
                continue
            label, essential, note = classify(info.filename)
            bucket = totals.setdefault(
                label,
                {"files": 0, "bytes": 0, "compressed": 0, "essential": essential, "note": note},
            )
            bucket["files"] = int(bucket["files"]) + 1
            bucket["bytes"] = int(bucket["bytes"]) + info.file_size
            bucket["compressed"] = int(bucket["compressed"]) + info.compress_size
            stored_total += info.file_size
            compressed_total += info.compress_size
            entries.append((info.file_size, info.filename))

    essential_bytes = sum(
        int(v["bytes"]) for v in totals.values() if v["essential"]
    )
    optional_bytes = stored_total - essential_bytes

    if arguments.json:
        print(
            json.dumps(
                {
                    "backup": str(arguments.backup),
                    "archive_bytes": arguments.backup.stat().st_size,
                    "uncompressed_bytes": stored_total,
                    "compressed_bytes": compressed_total,
                    "essential_bytes": essential_bytes,
                    "regenerable_bytes": optional_bytes,
                    "categories": totals,
                    "application_version": manifest.get("software", {}).get("version", ""),
                },
                indent=2,
                sort_keys=True,
            )
        )
        return 0

    print(f"Backup   : {arguments.backup}")
    print(f"On disk  : {human(arguments.backup.stat().st_size)}")
    print(f"Contents : {human(stored_total)} uncompressed across {len(entries):,} files")
    version = manifest.get("software", {}).get("version", "")
    if version:
        print(f"Written by Pole Position {version}")
    print()

    ordered = sorted(totals.items(), key=lambda item: int(item[1]["bytes"]), reverse=True)
    width = max(len(label) for label, _ in ordered)
    print(f"{'Category'.ljust(width)}  {'Size':>12}  {'Share':>7}  {'Files':>7}  Needed")
    print("-" * (width + 44))
    for label, bucket in ordered:
        size = int(bucket["bytes"])
        share = (size / stored_total * 100) if stored_total else 0.0
        needed = "yes" if bucket["essential"] else "no"
        print(
            f"{label.ljust(width)}  {human(size):>12}  {share:6.1f}%  "
            f"{int(bucket['files']):>7,}  {needed}"
        )
    print("-" * (width + 44))
    print(f"{'Required to commission'.ljust(width)}  {human(essential_bytes):>12}")
    print(f"{'Regenerable or legacy'.ljust(width)}  {human(optional_bytes):>12}")
    print()

    for label, bucket in ordered:
        if not bucket["essential"] and int(bucket["bytes"]):
            print(f"  {label}: {bucket['note']}")
    print()

    if arguments.top > 0:
        print(f"Largest {arguments.top} entries:")
        for size, name in sorted(entries, reverse=True)[: arguments.top]:
            print(f"  {human(size):>12}  {name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
